version: "3.8"  # optional since v1.27.0
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db123
      MYSQL_DATABASE: todo4
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "8090:3306"
    volumes:
      - dbdata:/var/lib/mysql
    # volumes:
    #   - /var/database/docker/common:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  backend:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "3030:3030"
    volumes:
      # - backend-data:/apps
      - .:/skyshi
      - /skyshi/node_modules
    environment:
      - DB_HOST=mysqldb
    tty: true
    stdin_open: true
volumes:
  dbdata:
